use_frameworks!

platform :ios, '10.0'

target 'TopSwiftExtension_Example' do
  pod 'TopSwiftExtension', :path => '../'

  target 'TopSwiftExtension_Tests' do
    inherit! :search_paths

    
  end
end
